[package]
name = "hayagriva-export-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
hayagriva = { version = "0.10.1", default-features = false, features = ["biblatex"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
